# Generated by Django 3.0.6 on 2021-04-11 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mobile', models.BigIntegerField(null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=64)),
                ('items', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
                ('store_link', models.CharField(default=uuid.uuid4, max_length=128)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanApp.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('mrp', models.CharField(max_length=64)),
                ('sale_price', models.CharField(max_length=64)),
                ('image', models.TextField(blank=True)),
                ('category', models.CharField(max_length=64)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanApp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', django.contrib.postgres.fields.jsonb.JSONField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dukaanApp.Customer')),
            ],
        ),
    ]
